version: "3.4"

services:
  pythonpoc-http:
    image: pythonpoc
    build:
      context: .
    volumes:
    - .:/code
    depends_on:
    - localstack
    - mongodb
    ports:
    - 5000:5000

  pythonpoc-consumers:
    image: pythonpoc
    build:
      context: .
    volumes:
    - .:/code
    depends_on:
    - localstack
    - mongodb
    environment:
    - ROLE_CONSUMER=true

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      # - SERVICES=${SERVICES- }
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  mongodb:
    image: mongo
    volumes:
      - ./volumes/mongodb:/data/
