version: "3.4"

services:
  http:
    image: pythonpoc
    build:
      context: .
    volumes:
    - .:/code
    depends_on:
    - localstack
    - mongodb
    - graphite
    ports:
    - 5000:5000

  consumers:
    image: pythonpoc
    build:
      context: .
    volumes:
    - .:/code
    depends_on:
    - localstack
    - mongodb
    - graphite
    environment:
    - ROLE_CONSUMER=true
    - PYTHONUNBUFFERED=true
    entrypoint:
    - python
    - consumers.py

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      # - SERVICES=${SERVICES- }
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  mongodb:
    image: mongo
    volumes:
      - ./volumes/mongodb:/data/

  mongoadmin:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongodb

  graphite:
    image: hopsoft/graphite-statsd
    ports:
    - 5080:80
    - 5081:81
    - 5002:8125
 